In [1]:
import numpy as np 
import pandas as pd
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 25
pd.options.display.max_columns = 20
pd.options.display.max_colwidth = 82
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10,6))
np.set_printoptions(precision=4, suppress=True)

In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [3]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [6]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [7]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [8]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [9]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [10]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [11]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [12]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                    [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [17]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [18]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [19]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [20]:
data[4] = np.nan

In [21]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [22]:
data.dropna(axis="columns", how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [23]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [24]:
df.iloc[:4, 1] = np.nan

In [25]:
df.iloc[:2, 2] = np.nan

In [26]:
df

0         1         2
0 -0.204708       NaN       NaN
1 -0.555730       NaN       NaN
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [27]:
df.dropna()

0         1         2
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [28]:
df.dropna(thresh=2)

0         1         2
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [29]:
df.fillna(0)

0         1         2
0 -0.204708  0.000000  0.000000
1 -0.555730  0.000000  0.000000
2  0.092908  0.000000  0.769023
3  1.246435  0.000000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [30]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.204708  0.500000  0.000000
1 -0.555730  0.500000  0.000000
2  0.092908  0.500000  0.769023
3  1.246435  0.500000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [31]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [32]:
df.iloc[2:, 1] = np.nan

In [33]:
df.iloc[4:, 2] = np.nan

In [34]:
df

0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772       NaN  1.343810
3 -0.713544       NaN -2.370232
4 -1.860761       NaN       NaN
5 -1.265934       NaN       NaN

In [35]:
df.fillna(method="ffill")

/var/folders/09/kwh57pm92_gfzd297vb_r36c0000gn/T/ipykernel_5796/3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")


0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772  0.124121  1.343810
3 -0.713544  0.124121 -2.370232
4 -1.860761  0.124121 -2.370232
5 -1.265934  0.124121 -2.370232

In [36]:
df.fillna(method="ffill", limit=2)

/var/folders/09/kwh57pm92_gfzd297vb_r36c0000gn/T/ipykernel_5796/1627181726.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", limit=2)


0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772  0.124121  1.343810
3 -0.713544  0.124121 -2.370232
4 -1.860761       NaN -2.370232
5 -1.265934       NaN -2.370232

In [37]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [39]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [40]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})

In [41]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [42]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [43]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [44]:
data["v1"] = range(7)

In [45]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [46]:
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [47]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [48]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [49]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [50]:
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon"
}

In [51]:
data["animal"] = data["food"].map(meat_to_animal)

In [52]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [53]:
def get_animal(x):
    return meat_to_animal[x]

In [54]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [55]:
data = pd.Series([1., -999, 2., -999, -1000, 3.])

In [56]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [59]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [60]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [61]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])

In [63]:
def transform(x):
    return x[:4].upper()

In [64]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [65]:
data.index = data.index.map(transform)

In [66]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [67]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [68]:
data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [69]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [70]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [71]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [72]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [73]:
pd.value_counts(age_categories)

/var/folders/09/kwh57pm92_gfzd297vb_r36c0000gn/T/ipykernel_5796/3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)


(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [74]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [75]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [76]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [77]:
data = np.random.uniform(size=20)

In [78]:
pd.cut(data, 4, precision=2)

[(0.34, 0.55], (0.34, 0.55], (0.76, 0.97], (0.76, 0.97], (0.34, 0.55], ..., (0.34, 0.55], (0.34, 0.55], (0.55, 0.76], (0.34, 0.55], (0.12, 0.34]]
Length: 20
Categories (4, interval[float64, right]): [(0.12, 0.34] < (0.34, 0.55] < (0.55, 0.76] < (0.76, 0.97]]

In [79]:
data = np.random.standard_normal(1000)

In [80]:
quartiles = pd.qcut(data, 4, precision=2)

In [81]:
quartiles

[(-0.026, 0.62], (0.62, 3.93], (-0.68, -0.026], (0.62, 3.93], (-0.026, 0.62], ..., (-0.68, -0.026], (-0.68, -0.026], (-2.96, -0.68], (0.62, 3.93], (-0.68, -0.026]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.96, -0.68] < (-0.68, -0.026] < (-0.026, 0.62] < (0.62, 3.93]]

In [83]:
pd.value_counts(quartiles)

/var/folders/09/kwh57pm92_gfzd297vb_r36c0000gn/T/ipykernel_5796/3472704981.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)


(-2.96, -0.68]     250
(-0.68, -0.026]    250
(-0.026, 0.62]     250
(0.62, 3.93]       250
Name: count, dtype: int64

In [84]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.9499999999999997, -1.187]    100
(-1.187, -0.0265]                400
(-0.0265, 1.286]                 400
(1.286, 3.928]                   100
Name: count, dtype: int64

In [85]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [86]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.049091     0.026112    -0.002544    -0.051827
std       0.996947     1.007458     0.995232     0.998311
min      -3.645860    -3.184377    -3.745356    -3.428254
25%      -0.599807    -0.612162    -0.687373    -0.747478
50%       0.047101    -0.013609    -0.022158    -0.088274
75%       0.756646     0.695298     0.699046     0.623331
max       2.653656     3.525865     2.735527     3.366626

In [88]:
col = data[2]

In [89]:
col[col.abs() > 3]

41    -3.399312
136   -3.745356
Name: 2, dtype: float64

In [90]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
41   0.457246 -0.025907 -3.399312 -0.974657
60   1.951312  3.260383  0.963301  1.201206
136  0.508391 -0.196713 -3.745356 -1.520113
235 -0.242459 -3.056990  1.918403 -0.578828
258  0.682841  0.326045  0.425384 -3.428254
322  1.179227 -3.184377  1.369891 -1.074833
544 -3.548824  1.553205 -2.186301  1.277104
635 -0.578093  0.193299  1.397822  3.366626
782 -0.207434  3.525865  0.283070  0.544635
803 -3.645860  0.255475 -0.549574 -1.907459

In [91]:
data[data.abs() > 3] = np.sign(data) * 2

In [92]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.052286     0.025567     0.000601    -0.051765
std       0.987762     0.994196     0.986353     0.990722
min      -2.989741    -2.970822    -2.881858    -2.969411
25%      -0.599807    -0.612162    -0.687373    -0.747478
50%       0.047101    -0.013609    -0.022158    -0.088274
75%       0.756646     0.695298     0.699046     0.623331
max       2.653656     2.954439     2.735527     2.628441

In [94]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0  1.0
1  1.0 -1.0  1.0 -1.0
2  1.0  1.0  1.0 -1.0
3 -1.0 -1.0  1.0 -1.0
4 -1.0  1.0 -1.0 -1.0

In [95]:
df = pd.DataFrame(np.arange(5 * 7).reshape(5, 7))

In [96]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [97]:
sampler = np.random.permutation(5)

In [98]:
sampler

array([3, 1, 4, 2, 0])

In [99]:
df.take(sampler)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6

In [100]:
df.iloc[sampler]

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6

In [101]:
column_sampler = np.random.permutation(7)

In [102]:
column_sampler

array([4, 6, 3, 2, 1, 0, 5])

In [103]:
df.take(column_sampler, axis="columns")

4   6   3   2   1   0   5
0   4   6   3   2   1   0   5
1  11  13  10   9   8   7  12
2  18  20  17  16  15  14  19
3  25  27  24  23  22  21  26
4  32  34  31  30  29  28  33

In [104]:
df.sample(n=3)

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6

In [105]:
choices = pd.Series([5, 7, -1, 6, 4])

In [106]:
choices.sample(n=10, replace=True)

2   -1
0    5
3    6
1    7
4    4
0    5
4    4
0    5
4    4
4    4
dtype: int64

In [107]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})

In [108]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [109]:
pd.get_dummies(df["key"])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [110]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [111]:
df_with_dummy = df[["data1"]].join(dummies)

In [112]:
df_with_dummy

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [113]:
mnames = ["movie_id", "title", "genres"]

In [114]:
movies = pd.read_table("/Users/ray/Documents/machine_learning_engineer/pydata-book-ch-ex/pydata-book/datasets/movielens/movies.dat",
                       sep="::", header=None, names=mnames, engine="python")

In [115]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [116]:
dummies = movies["genres"].str.get_dummies("|")

In [118]:
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [119]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [120]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [121]:
np.random.seed(12345)

In [122]:
values = np.random.uniform(size=10)

In [123]:
values

array([0.9296, 0.3164, 0.1839, 0.2046, 0.5677, 0.5955, 0.9645, 0.6532,
       0.7489, 0.6536])

In [124]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [125]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [126]:
s = pd.Series([1, 2, 3, None])

In [127]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [128]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [129]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [130]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [131]:
s.dtype

Int64Dtype()

In [132]:
s[3] is pd.NA

True

In [133]:
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [135]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [136]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [137]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [138]:
df = pd.DataFrame({"A": [1, 2, None, 4], 
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})

In [139]:
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [140]:
df["A"] = df["A"].astype("Int64")

In [141]:
df["B"] = df["B"].astype("string")

In [142]:
df["C"] = df["C"].astype("boolean")

In [143]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

In [144]:
val = "a,b,  guido"

In [145]:
val.split(",")

['a', 'b', '  guido']

In [146]:
pieces = [x.strip() for x in val.split(",")]

In [147]:
pieces

['a', 'b', 'guido']

In [148]:
first, second, third = pieces

In [149]:
first + "::" + second + "::" + third

'a::b::guido'

In [150]:
"guido" in val

True

In [151]:
val.index(",")

1

In [152]:
val.find(":")

-1

In [153]:
val.index(":")

ValueError: substring not found

In [154]:
val.count(",")

2

In [155]:
val.replace(",", "::")

'a::b::  guido'

In [157]:
val.replace(",", "")

'ab  guido'

In [158]:
import re

In [159]:
text = "foo    bar\t baz \tqux"

In [160]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [161]:
regex = re.compile(r"\s+")

In [162]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [163]:
regex.findall(text)

['    ', '\t ', ' \t']

In [164]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [165]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [166]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [167]:
m = regex.search(text)

In [168]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [169]:
text[m.start():m.end()]

'dave@google.com'

In [170]:
print(regex.match(text))

None


In [171]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [179]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [180]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [181]:
m = regex.match("wesm@bright.net")

In [182]:
m.groups()

('wesm', 'bright', 'net')

In [183]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [184]:
print(regex.sub("Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: , Domain: , Suffix: 
Steve Username: , Domain: , Suffix: 
Rob Username: , Domain: , Suffix: 
Ryan Username: , Domain: , Suffix: 


In [185]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com", "Rob": "rob@gmail.com", "Wes": np.nan}

In [186]:
data = pd.Series(data)

In [187]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [188]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [189]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [190]:
data_as_string_ext = data.astype('string')

In [191]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [192]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [193]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [194]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [195]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [196]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [197]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [198]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [199]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [200]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)

In [201]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [202]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [203]:
pd.value_counts(values)

/var/folders/09/kwh57pm92_gfzd297vb_r36c0000gn/T/ipykernel_5796/3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


apple     6
orange    2
Name: count, dtype: int64

In [204]:
values = pd.Series([0, 1, 0, 0] * 2)

In [205]:
dim = pd.Series(['apple', 'orange'])

In [206]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [207]:
dim

0     apple
1    orange
dtype: object

In [208]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [209]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [210]:
N = len(fruits)

In [211]:
rng = np.random.default_rng(seed=12345)

In [212]:
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                   columns=['basket_id', 'fruit', 'count', 'weight'])

In [213]:
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [215]:
fruit_cat = df['fruit'].astype('category')

In [216]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [218]:
c = fruit_cat.array

In [219]:
type(c)

pandas.core.arrays.categorical.Categorical

In [220]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [221]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [222]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [223]:
df['fruit'] = df['fruit'].astype('category')

In [224]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [225]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [226]:
my_categories 

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [227]:
categories = ['foo', 'bar', 'baz']

In [228]:
codes = [0, 1, 2, 0, 0, 1]

In [229]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [230]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [231]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [232]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [233]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [234]:
rng = np.random.default_rng(seed=12345)

In [235]:
draws = rng.standard_normal(1000)

In [236]:
draws[:5]

array([-1.4238,  1.2637, -0.8707, -0.2592, -0.0753])

In [237]:
bins = pd.qcut(draws, 4)

In [238]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [239]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [240]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [241]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [242]:
bins = pd.Series(bins, name='quartile')

In [243]:
results = (pd.Series(draws)
           .groupby(bins)
           .agg(['count', 'min', 'max'])
           .reset_index())

/var/folders/09/kwh57pm92_gfzd297vb_r36c0000gn/T/ipykernel_5796/1248366115.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(bins)


In [244]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [245]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [246]:
N = 10_000_000

In [247]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux' * (N // 4)])

In [248]:
categories = labels.astype('category')

In [250]:
labels.memory_usage(deep=True)

7500369

In [251]:
categories.memory_usage(deep=True)

7500545

In [252]:
%time _ = labels.astype('category')

CPU times: user 38.1 ms, sys: 1.68 ms, total: 39.8 ms
Wall time: 37.8 ms


In [253]:
%timeit labels.value_counts()

36.7 µs ± 607 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [255]:
%timeit categories.value_counts()

54.5 µs ± 448 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [256]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [257]:
cat_s = s.astype('category')

In [258]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [259]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [260]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [261]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [262]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [263]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [264]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [265]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [266]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [267]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [268]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [269]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [270]:
pd.get_dummies(cat_s)

a      b      c      d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True